# Generated by Django 4.2 on 2024-09-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=50, unique=True), max_length=50, null=True, unique=True),
        ),
    ]
