# Generated by Django 4.2 on 2024-09-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='2fa_code'),
        ),
    ]
