# Generated by Django 4.2 on 2024-09-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_nickname'),
        ('users', '0014_customuser_is_verified'),
    ]

    operations = [
    ]
