version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    networks:
      - transcendence
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  django:
    build: .
    image: django:transcendence
    container_name: django
    networks:
      - transcendence
    volumes:
      - static_volume:/ft_transcendence/static
      - media_volume:/ft_transcendence/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendence.settings
    depends_on:
      - db
      - hardhat
    ports:
      - "8000:8000"

  hardhat:
    build: ./blockchain
    image: hardhat:transcendence
    container_name: hardhat
    networks:
      - transcendence
    ports:
      - "8545:8545"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    image: nginx:transcendence
    volumes:
      - media_volume:/var/www/html/media
      - static_volume:/var/www/html/static
    depends_on:
      - django
    networks:
      - transcendence
    ports:
      - "5000:5000"
      - "5001:443"

networks:
  transcendence:
    name: transcendence

volumes:
  db_volume:
    name: db_volume
  static_volume:
    name: static_volume
  media_volume:
    name: media_volume