# Generated by Django 4.2 on 2024-09-28 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_initial'),
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(related_name='tournaments', to='match.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='num_players',
            field=models.PositiveSmallIntegerField(choices=[(4, '4 Players'), (8, '8 Players')], default=2),
            preserve_default=False,
        ),
    ]
