# Generated by Django 4.2 on 2024-09-12 21:03

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_invitelobby_tournament_owner_delete_tournamentplayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start'),
        ),
    ]
