# Generated by Django 4.2 on 2024-09-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournament_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='token',
            field=models.CharField(default='e4365a', max_length=6),
        ),
    ]
