# Generated by Django 4.2 on 2024-09-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_remove_tournament_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
