# Generated by Django 4.2 on 2024-09-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('score_user1', models.IntegerField(default=0, verbose_name='score player 1')),
                ('score_user2', models.IntegerField(default=0, verbose_name='score player 2')),
                ('is_tournament', models.BooleanField(default=False)),
            ],
        ),
    ]
