# Generated by Django 4.2 on 2024-09-03 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date started')),
                ('date_ended', models.DateTimeField(blank=True, null=True, verbose_name='date ended')),
                ('score_user1', models.IntegerField(default=0, verbose_name='score player 1')),
                ('score_user2', models.IntegerField(default=0, verbose_name='score player 2')),
                ('is_tournament', models.BooleanField(default=False)),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('user1', 'user2', 'date_started'), name='unique_match'),
        ),
    ]
