# Generated by Django 4.2 on 2024-09-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_number',
        ),
    ]
