# Generated by Django 4.2 on 2024-09-26 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_match_user1_alter_match_user2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_match',
        ),
        migrations.RemoveField(
            model_name='match',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='match',
            name='date_started',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('user1', 'user2', 'date'), name='unique_match'),
        ),
    ]
