# Generated by Django 4.2 on 2024-09-27 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_players'),
        ('match', '0006_remove_match_unique_match_remove_match_date_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament'),
        ),
    ]
