# Generated by Django 4.2 on 2024-09-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_match_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
    ]
