# Generated by Django 4.2 on 2024-09-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_alter_ranking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
