# Generated by Django 4.2 on 2024-09-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_alter_ranking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='win_rate',
        ),
    ]
