# Generated by Django 4.2 on 2024-09-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_remove_ranking_win_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
