# Generated by Django 4.2 on 2024-09-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_ranking_win_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='win_rate',
        ),
    ]
